# Generated by Django 3.2.7 on 2021-11-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('desc', models.CharField(max_length=100, verbose_name='Category description')),
            ],
        ),
        migrations.CreateModel(
            name='UploadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Product Image')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('price', models.IntegerField(default=0, verbose_name='Product Price')),
                ('description', models.TextField(default='null value', verbose_name='Product Description')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='null value', max_length=100, verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(default=1234567, max_length=100, verbose_name='Enter your name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='null value', on_delete=django.db.models.deletion.CASCADE, to='userapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Product Price'),
        ),
    ]
