# Generated by Django 3.2.7 on 2021-11-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100, verbose_name='ProductName')),
                ('category', models.CharField(max_length=100, verbose_name='ProductCategory')),
                ('productprice', models.IntegerField(verbose_name='ProductPrice')),
                ('description', models.CharField(max_length=200, verbose_name='ProductDescription')),
                ('productimage', models.ImageField(upload_to='productuploads', verbose_name='ProductImage')),
            ],
        ),
    ]
