# Generated by Django 3.2.7 on 2021-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ProductName')),
                ('feature', models.CharField(max_length=100, verbose_name='ProductCategory')),
                ('description', models.CharField(max_length=200, verbose_name='ProductDescription')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadproduct',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Default Category'),
        ),
    ]
