# Generated by Django 3.2.7 on 2021-11-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultx', '0002_auto_20211105_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProduct_02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100, verbose_name='ProductName')),
                ('productprice', models.IntegerField(verbose_name='ProductPrice')),
                ('description', models.CharField(max_length=200, verbose_name='ProductDescription')),
                ('productimage', models.ImageField(upload_to='productuploads', verbose_name='ProductImage')),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultx.uploadcategories')),
            ],
        ),
    ]
